language: rust
cache: cargo
rust:
- stable
os:
- linux
- osx
- windows
script:
- cargo build --verbose --release
- cargo test --verbose
matrix:
  fast_finish: true
before_deploy: mkdir -p target/release/artifacts && if [ "$TRAVIS_OS_NAME" == "windows" ]; then cp target/release/waterbear.exe target/release/artifacts/waterbear-${TRAVIS_OS_NAME}.exe; else cp target/release/waterbear target/release/artifacts/waterbear-$TRAVIS_OS_NAME; fi
deploy:
  provider: releases
  api_key:
    secure: jE9u+Y5n4twL1mnEQwZCxv0iUu5/VbOqdgi11Bq7+cHKEuDi3P2gCk8tqoVIB9D2V3B/YgXBxJtMQ88Ry2cQ/cDKCBKN/5VRdD7MyWjLQD1CciTHgj2hQK54ltQ9CSjqAwt5IJKjbYBMjKfVq1lSXTeyOlppq5P/QhxsRHKFZ1Pe2M31Dr5+aS1QYOtGAtdvgzPqW9gIrKx9rH9UALmaBZsQxwti6FUEAqHs5R0GYqYTVGuk1bL2r3PICPyizCbCw0PbIuMQS7SC7TAB4qtNNkK7e9nOIdl7FJYWIfk2orW8lmaUlowPPYMXARkKzKmVDl+34gDMJE8/RBHzk9/LYqNFvzVe29LW8fKfxlltABcJtFxO+c/i7inzmUo+4GzAEc7XkH3SC2YQapdqB806sfi2pBY+1p5iPOABjx2JW55g/GAkXd9FxAaHdZTAsxPHJztD5f095oQeYDWjJ5J1+eBwUqznkCF0DAG5SfH1ReIQha7Ethn3LeWK6pael3IogOmuMOdW7HUcu/JoeQdfe3oxAZ8bN8qvHy92EamgPI53UUDKwevkdpDg2pTOmdlTpFPv81GjfdrdKiXDZTa2qiyg1jnnNj8M8HBD4GYxMiy3K4eMFr2s4kj28CsYlXMeaaz2yYlhRgCQZma68p24HFyDsnNg82q1LtnGHeUjrDg=
  file_glob: true
  file: target/release/artifacts/*
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
    repo: wtetzner/waterbear

