language: rust
cache: cargo
script:
- cargo build --verbose --release
- cargo test --verbose
os:
- linux
- osx
rust:
- stable
- beta
- nightly
matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-musl
  allow_failures:
  - rust: nightly
  fast_finish: true
before_deploy: cp target/release/waterbear target/release/waterbear-$TRAVIS_RUST_VERSION
deploy:
  provider: releases
  api_key:
    secure: TGPUPwLwBZ1NtJ6lDMxSChenodSqbIq5ZxJesTE3LmOfzgwtdpJ0eC44s7qb1F0v/yZ+4aanCcSo0mB9iVDjGeaTBXkTgBRf4TYHp7X+bLakGUIHphyH1FO5usKun0nmOTaUHytqQ0x4SCF238r42LgU/9kZSKDofwWJoYKNsaK7uB/MITJ+eMlU509cXuTYxr33+Ta8xPkUQe5yKU6VK6q3DxhJdpbEvQNrQW+oJDL/MGxopKqNutCM5MCAorYhjHxwUpqg5Z4cPjjwf3928Me0UlGrGxaWqIenQUb/sUU+ofH5Jjs6grhnO3WjIc3nSn20oaAtDL0rhRPApm5boJ/sZR52LS87zrBr++OTNZjfhvDPfN4ccpR5Hj11ZdmVKOEAahDg61GX+xkmABWmKPcL3TqkyfM9I9BvYW5bVs9jFxPrFphv54vaSzpDlThBceNhgG8yaRoeAcZd9L1YnTorVivHrdISeqfXHs4xfe6q2nUhlNjO+F6GHCj3fiNnzp7QDtgeEUHnLcwD3Cm6x7iFvg9/gg/t3A+bwGc30aBJ22Vx21aBQtuuBKHvj8P9yjmM/TIpGi7OCQhKaZx835BbqAzQtxDAe9AoaJDFVpMSykHIGSRopKzgYsrQslsQWzZXgtHi3QPtIat8pcIVhgaRSziUUwB23p5vq8b7QDU=
  file: target/release/waterbear-$TRAVIS_RUST_VERSION
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable
    repo: wtetzner/waterbear
