[package]
name = "wombat"
version = "0.1.0"
authors = ["Walter Tetzner <walter@waltertetzner.net>"]

[dependencies]
bit-vec = "*"
clap = "^2.0"

[dependencies.nom]
version = "^2.0"
features = ["regexp", "verbose-errors"]

