[package]
name = "wombat-vmu-asm"
description = "Assembler for the Dreamcast VMU"
version = "0.1.0"
authors = ["Walter Tetzner <walter@waltertetzner.net>"]

[dependencies]
unicode-segmentation = "1.2.0"
bit-vec = "*"
clap = "2.26.2"
pest = "0.4"
regex = "*"

[lib]
name = "wombat_vmu_asm"
path = "src/asm.rs"

[[bin]]
name = "wombat-vmu-asm"
path = "src/main.rs"
