[package]
name = "waterbear"
description = "Assembler/Disassembler for the Dreamcast VMU"
version = "0.8.0"
authors = ["Walter Tetzner <walter@waltertetzner.net>"]

[dependencies]
lazy_static = "1.0"
unicode-segmentation = "1.2.0"
unicode_categories = "*"
clap = "*"
regex = "*"
termcolor = "1"
atty = "0.2"
uuid = { version = "*", features = ["v4"] }

# custom derives
instruction-derive = { path = "instruction-derive" }

[lib]
name = "waterbear"
path = "src/lib.rs"

[[bin]]
name = "waterbear"
path = "src/main.rs"
