[package]
name = "waterbear"
description = "Assembler for the Dreamcast VMU"
version = "0.1.0"
authors = ["Walter Tetzner <walter@waltertetzner.net>"]

[dependencies]
lazy_static = "1.0"
unicode-segmentation = "1.2.0"
unicode_categories = "*"
bit-vec = "*"
clap = "*"
pest = "0.4"
regex = "*"

[lib]
name = "waterbear"
path = "src/asm.rs"

[[bin]]
name = "waterbear"
path = "src/main.rs"
