[package]
name = "waterbear-instruction-derive"
version = "0.1.0"
authors = ["Walter Tetzner <walter@waltertetzner.net>"]

[dependencies]
syn = "0.11"
quote = "0.3"
regex = "1.0"
lazy_static = "1.0"

[lib]
proc-macro = true

